<!-- TODO -->
Look at making a model to predict Make/Model/Year all in one
A model then that does each part of the overall prediction independentlty

In [3]:
from scipy.io import loadmat
import os

In [9]:
parent_folder = '../../../data/Car Labelling/Standford Dataset/car_devkit/devkit'


In [13]:
car_meta_mat_file_path = os.path.join(parent_folder,'cars_meta.mat')
car_meta_mat = loadmat(car_meta_mat_file_path)

In [28]:
print(car_meta_mat['class_names'][0][14])

['Audi R8 Coupe 2012']


In [33]:
print(car_meta_mat['class_names'][0][3])

['Acura TL Type-S 2008']


In [38]:
print(car_meta_mat['class_names'][0][134])

['Hyundai Elantra Sedan 2007']


In [41]:
print(car_meta_mat['class_names'][0][106])

['Ford Mustang Convertible 2007']


In [ ]:
car_train_mat_file_path = os.path.join(parent_folder,'cars_train_annos.mat')
car_train_mat = loadmat(car_train_mat_file_path)

In [46]:
def car_lookup(index):
    return car_meta_mat['class_names'][0][index]

In [49]:
for i in range(10):
    car_index = car_train_mat['annotations'][0][i][0][0][0]
    print(car_lookup(car_index))

['Bentley Arnage Sedan 2009']
['BMW X3 SUV 2012']
['Dodge Ram Pickup 3500 Crew Cab 2010']


IndexError: index 621 is out of bounds for axis 0 with size 196

In [51]:
car_train_mat['annotations'][0][0]

np.void((array([[39]], dtype=uint8), array([[116]], dtype=uint8), array([[569]], dtype=uint16), array([[375]], dtype=uint16), array([[14]], dtype=uint8), array(['00001.jpg'], dtype='<U9')), dtype=[('bbox_x1', 'O'), ('bbox_y1', 'O'), ('bbox_x2', 'O'), ('bbox_y2', 'O'), ('class', 'O'), ('fname', 'O')])

In [30]:
car_train_mat['annotations'][0][0][-2]

array([[14]], dtype=uint8)

In [32]:
car_train_mat['annotations'][0][1][-2]

array([[3]], dtype=uint8)

In [37]:
car_train_mat['annotations'][0][3][-2]

array([[134]], dtype=uint8)

In [42]:
car_train_mat['annotations'][0][4]

np.void((array([[14]], dtype=uint8), array([[36]], dtype=uint8), array([[133]], dtype=uint8), array([[99]], dtype=uint8), array([[106]], dtype=uint8), array(['00005.jpg'], dtype='<U9')), dtype=[('bbox_x1', 'O'), ('bbox_y1', 'O'), ('bbox_x2', 'O'), ('bbox_y2', 'O'), ('class', 'O'), ('fname', 'O')])

In [44]:
car_train_mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013',
 '__version__': '1.0',
 '__globals__': [],
 'annotations': array([[(array([[39]], dtype=uint8), array([[116]], dtype=uint8), array([[569]], dtype=uint16), array([[375]], dtype=uint16), array([[14]], dtype=uint8), array(['00001.jpg'], dtype='<U9')),
         (array([[36]], dtype=uint8), array([[116]], dtype=uint8), array([[868]], dtype=uint16), array([[587]], dtype=uint16), array([[3]], dtype=uint8), array(['00002.jpg'], dtype='<U9')),
         (array([[85]], dtype=uint8), array([[109]], dtype=uint8), array([[601]], dtype=uint16), array([[381]], dtype=uint16), array([[91]], dtype=uint8), array(['00003.jpg'], dtype='<U9')),
         ...,
         (array([[26]], dtype=uint8), array([[246]], dtype=uint8), array([[660]], dtype=uint16), array([[449]], dtype=uint16), array([[163]], dtype=uint8), array(['08142.jpg'], dtype='<U9')),
         (array([[78]], dtype=uint8), array([[526]], dtype=uint16), 