In [1]:
%matplotlib inline

import cv2
from matplotlib import pyplot as plt
import torch
from PIL import Image
import numpy as np
from ultralytics import YOLO

torch.cuda.is_available()
torch.cuda.device_count()

1

In [6]:
model = YOLO('yolov8n.pt') 

In [3]:
image_2 = cv2.imread('../../data/Car Detection/Dataset_2/Data/Data/train/car85.jpg')

In [20]:
results = model('../../data/Car Detection/Dataset_2/Data/Data/train/car85.jpg')


image 1/1 c:\Users\joshu_rdnqgbx\Documents\Current Work\Car Recognition Model\Car Detection\experimentation\..\..\data\Car Detection\Dataset_2\Data\Data\train\car85.jpg: 448x640 4 cars, 39.8ms
Speed: 4.2ms preprocess, 39.8ms inference, 2.4ms postprocess per image at shape (1, 3, 448, 640)


In [21]:
results[0].boxes.data

tensor([[1.7373e-01, 2.3087e+00, 5.7439e+02, 5.2081e+02, 7.9342e-01, 2.0000e+00],
        [2.6321e+02, 2.0414e+01, 5.5597e+02, 2.0402e+02, 6.7106e-01, 2.0000e+00],
        [4.0504e+02, 2.8212e+01, 5.9060e+02, 1.9997e+02, 5.9448e-01, 2.0000e+00],
        [4.5526e+02, 6.7162e+00, 5.8235e+02, 1.0870e+02, 5.7479e-01, 2.0000e+00]], device='cuda:0')

In [ ]:
car_preds = [pred for pred in results[0].boxes.data.cpu().numpy() if pred[-1] ==2]
car_preds

[array([    0.17373,      2.3087,      574.39,      520.81,     0.79342,           2], dtype=float32),
 array([     263.21,      20.414,      555.97,      204.02,     0.67106,           2], dtype=float32),
 array([     405.04,      28.212,       590.6,      199.97,     0.59448,           2], dtype=float32),
 array([     455.26,      6.7162,      582.35,       108.7,     0.57479,           2], dtype=float32)]