In [1]:
%matplotlib inline

import pandas as pd
import cv2
from matplotlib import pyplot as plt
import torch
import numpy as np
import os
import xml.etree.ElementTree as ET
from torchvision.models.detection import fasterrcnn_resnet50_fpn_v2, FasterRCNN_ResNet50_FPN_V2_Weights
from torchvision.io.image import decode_image
from torchvision.utils import draw_bounding_boxes
from torchvision.transforms.functional import to_pil_image

torch.cuda.is_available()
torch.cuda.device_count()

1

In [ ]:
weights = FasterRCNN_ResNet50_FPN_V2_Weights.DEFAULT
model = fasterrcnn_resnet50_fpn_v2(weights=weights, box_score_thresh=0.6)
model.eval()

FasterRCNN(
  (transform): GeneralizedRCNNTransform(
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
      Resize(min_size=(800,), max_size=1333, mode='bilinear')
  )
  (backbone): BackboneWithFPN(
    (body): IntermediateLayerGetter(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
       

In [4]:
preprocess = weights.transforms()

In [3]:
parent_folder = '../../data/Car Detection/Dataset_2/Data/Data/train/'

In [7]:
prediction

{'boxes': tensor([[1.5460e+01, 1.3653e+02, 7.8739e+02, 5.0940e+02],
         [1.8404e+02, 9.4955e+01, 2.2879e+02, 1.8424e+02],
         [3.4552e-01, 1.1611e+02, 4.2281e+01, 2.4802e+02],
         [4.7438e+01, 1.4645e+02, 1.9500e+02, 1.9506e+02],
         [5.3221e+02, 1.2218e+02, 7.9761e+02, 2.6828e+02],
         [6.4599e+02, 1.1139e+02, 6.7283e+02, 1.4583e+02],
         [1.5887e+02, 1.2109e+02, 1.7595e+02, 1.5270e+02],
         [3.9632e+01, 1.2520e+02, 6.1690e+01, 1.5189e+02],
         [5.7882e+01, 1.2188e+02, 7.5657e+01, 1.5340e+02],
         [6.2882e+02, 1.1452e+02, 6.4062e+02, 1.4110e+02],
         [4.2151e+02, 1.3873e+02, 5.1955e+02, 1.6258e+02],
         [3.5706e+02, 1.2210e+02, 3.6940e+02, 1.4412e+02],
         [3.4140e+02, 1.2302e+02, 3.5605e+02, 1.4398e+02],
         [6.7190e+02, 1.1625e+02, 6.8649e+02, 1.4799e+02],
         [5.1265e+02, 1.2202e+02, 5.2297e+02, 1.3904e+02],
         [4.7018e+02, 1.2041e+02, 4.8449e+02, 1.3894e+02],
         [3.2247e+01, 1.6829e+02, 1.1766e+02, 2

In [51]:
prediction

{'boxes': tensor([[158.0078,  55.8940, 641.8944, 461.8629],
         [421.4464,  84.0862, 508.1002, 133.9796],
         [ 84.1223, 122.5425,  96.1794, 148.4470],
         [113.2329, 207.1099, 124.0371, 234.0980],
         [ 88.7430, 157.4297, 103.4793, 191.8707],
         [305.1731,  86.2281, 348.2599, 129.2526],
         [100.5786, 209.5933, 113.8846, 234.3434],
         [ 88.3641, 206.3847, 100.6759, 229.3879],
         [110.3391, 156.6293, 127.0726, 190.9846],
         [ 84.3870,  34.9277,  94.0276,  58.9417],
         [312.9398,  85.7043, 379.7892, 131.1289],
         [ 76.4963, 211.5443,  88.3683, 234.9789],
         [475.6958,  61.3493, 525.7490, 109.6041],
         [123.0535, 210.5036, 135.4282, 234.9242],
         [464.3293,  93.2823, 508.3011, 133.0651],
         [ 73.3787,  36.2246,  82.5199,  59.4406],
         [ 87.5839,  77.0555,  99.8264, 105.7931],
         [101.2729,  31.7103, 113.3139,  60.3332]], grad_fn=<StackBackward0>),
 'labels': tensor([ 3,  1, 44, 44, 44,  1, 44

In [ ]:
prediction['scores'][0]

tensor(0.9868, grad_fn=<SelectBackward0>)

In [55]:
for file in os.listdir(parent_folder):
    if file.endswith('xml'):
        continue
    full_image_path = os.path.join(parent_folder,file)
    image = decode_image(full_image_path)
    batch = [preprocess(image)]
    prediction = model(batch)[0]

    main_car = []
    for boxes,labels in zip(prediction['boxes'],prediction['labels']):
        if labels == 3:
            main_car = boxes.reshape(1,-1)
        break
    
    print(main_car,prediction['scores'][0])
    # labels = [weights.meta["categories"][i] for i in prediction["labels"]]
    if len(main_car) == 0:
        image = cv2.imread(full_image_path)
        cv2.imshow('Image', image) 
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        continue
    box = draw_bounding_boxes(image, boxes=main_car,
                            # labels=labels,
                            colors="red",
                            width=4, font_size=30)
    im = to_pil_image(box.detach())
    im.show()

    plt.show()

tensor([[188.3381, 248.4753, 711.4306, 457.2341]], grad_fn=<ViewBackward0>) tensor(0.9992, grad_fn=<SelectBackward0>)


c:\Users\joshu_rdnqgbx\anaconda3\envs\FNB_env\Lib\site-packages\torchvision\utils.py:233: UserWarning: Argument 'font_size' will be ignored since 'font' is not set.
  warnings.warn("Argument 'font_size' will be ignored since 'font' is not set.")


tensor([[ 13.1466,  99.7777, 553.2121, 338.3369]], grad_fn=<ViewBackward0>) tensor(0.9897, grad_fn=<SelectBackward0>)
tensor([[109.2860, 160.0614, 726.8569, 545.1077]], grad_fn=<ViewBackward0>) tensor(0.8925, grad_fn=<SelectBackward0>)
tensor([[721.2365, 239.7546, 768.3474, 257.1244]], grad_fn=<ViewBackward0>) tensor(0.9745, grad_fn=<SelectBackward0>)
[] tensor(0.9931, grad_fn=<SelectBackward0>)
[] tensor(0.9985, grad_fn=<SelectBackward0>)
tensor([[413.9363, 294.2239, 623.3333, 418.3088]], grad_fn=<ViewBackward0>) tensor(0.9992, grad_fn=<SelectBackward0>)
tensor([[ 46.1840, 166.5024, 709.7131, 472.1815]], grad_fn=<ViewBackward0>) tensor(0.9993, grad_fn=<SelectBackward0>)
tensor([[158.0078,  55.8940, 641.8944, 461.8629]], grad_fn=<ViewBackward0>) tensor(0.9868, grad_fn=<SelectBackward0>)
[] tensor(0.9993, grad_fn=<SelectBackward0>)
tensor([[ 15.4599, 136.5331, 787.3873, 509.3979]], grad_fn=<ViewBackward0>) tensor(0.9997, grad_fn=<SelectBackward0>)
tensor([[711.5833,  94.2779, 798.9999, 

KeyboardInterrupt: 